title: Anuj Kumar Singh
description: Developer Portfolio â€” Projects, Articles, and Technical Demonstrations
url: https://anujsinghk.github.io
baseurl: ""

author:
  name: Anuj Kumar Singh
  email: singh.anuj256@gmail.com

collections:
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /articles/:name/

markdown: kramdown

plugins:
  - jekyll-sitemap
